multi_chomp_node:
  ros__parameters:
    num_robots: 6
    waypoints_per_robot: 1000
    dt: 1.0
    eta: 0.5        # learning rate
    lambda: 10.0       # smoothness 
    mu: 100.0          # Obstacle/Collision weight
    robot_radius: 0.4
    obstacle_max_dist: 3.0